import { Router } from 'express';
import { authRouter } from './auth';
import { meRouter } from './me';
import { spacesRouter } from './spaces';
import { walletRouter } from './wallet';
import { duesRouter } from './dues';
import { transactionsRouter, paymentsRouter } from './transactions';
import { webhooksRouter } from './webhooks';
import { notificationsRouter } from './notifications';
import { pollsPublicRouter } from './polls';
import { adminRouter } from './admin';
import { referralsRouter } from './referrals';
import { disputesRouter } from './disputes';
import { banksRouter } from './banks';
import { assistantRouter } from './assistant';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/me', meRouter);
apiRouter.use('/spaces', spacesRouter);
apiRouter.use('/wallet', walletRouter);
apiRouter.use('/dues', duesRouter);
apiRouter.use('/transactions', transactionsRouter);
apiRouter.use('/payments', paymentsRouter);
apiRouter.use('/webhooks', webhooksRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/polls', pollsPublicRouter);
apiRouter.use('/admin', adminRouter);
apiRouter.use('/referrals', referralsRouter);
apiRouter.use('/disputes', disputesRouter);
apiRouter.use('/banks', banksRouter);
apiRouter.use('/assistant', assistantRouter);
